# Generated by Django 4.2.3 on 2023-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title...', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('context', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
